DEBUG = False
SECRET_KEY = 'SUPERSECRETKEYHIHI'
CLIENT_ID = ''
CLIENT_SECRET = ''

OAUTH_ENDPOINT_AUTHORIZE = 'http://localhost:8000/auth/authorize/'
OAUTH_ENDPOINT_TOKEN = 'http://localhost:8000/auth/token/'
OAUTH_ENDPOINT_REFRESH = OAUTH_ENDPOINT_TOKEN
